name: Update Data

on: [push]

concurrency: 1

jobs:

  Download-Exchange-Data:
    runs-on: ubuntu-latest
    timeout-minutes: 90
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Prep Git
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

      - name: Binance Backtesting Variables
        id: binance-dates
        uses: falti/dotenv-action@v0.2.6
        with:
          log-variables: true
          path:
            backtesting-binance.env

      - name: Download Binance Data (${{ steps.binance-dates.outputs.start_date }} - ${{ steps.binance-dates.outputs.end_date }})
        id: binance-data-download
        env:
          START_DATE: ${{ steps.binance-dates.outputs.start_date }}
          END_DATE: ${{ steps.binance-dates.outputs.end_date }}
          EXCHANGE: binance
        run: |
          docker-compose run --rm download-data

      - name: Fix File Ownership
        run: |
          sudo chown -R $(id -u):$(id -g) .

      - name: Commit Binance Changed Files
        id: commit-binance-changes
        if: steps.binance-data-download.outcome == 'success'
        continue-on-error: true
        run: |
          git add binance/*.json
          git commit -a -m "Update Binance exchange data from ${{ steps.binance-dates.outputs.start_date }} to ${{ steps.binance-dates.outputs.end_date }}"

      - name: Kucoin Backtesting Variables
        id: kucoin-dates
        uses: falti/dotenv-action@v0.2.6
        with:
          log-variables: true
          path:
            backtesting-kucoin.env

      - name: Download Kucoin Data (${{ steps.kucoin-dates.outputs.start_date }} - ${{ steps.kucoin-dates.outputs.end_date }})
        id: kucoin-data-download
        env:
          START_DATE: ${{ steps.kucoin-dates.outputs.start_date }}
          END_DATE: ${{ steps.kucoin-dates.outputs.end_date }}
          EXCHANGE: kucoin
        run: |
          docker-compose run --rm download-data

      - name: Fix File Ownership
        run: |
          sudo chown -R $(id -u):$(id -g) .

      - name: Commit Kucoin Changed Files
        id: commit-kucoin-changes
        if: steps.kucoin-data-download.outcome == 'success'
        continue-on-error: true
        run: |
          git add kucoin/*.json
          git commit -a -m "Update Kucoin exchange data from ${{ steps.kucoin-dates.outputs.start_date }} to ${{ steps.kucoin-dates.outputs.end_date }}"

      - name: Push changes
        uses: ad-m/github-push-action@master
        if: steps.commit-binance-changes.outcome == 'success' || steps.commit-kucoin-changes.outcome == 'success'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
